new landing page, transfer pdf blob and tg nick
nekromant322/review-report-bot pull request #33
Opened 2024-04-14 11:38 UTC by Vladislav812

first steps done:
- new stolen landing page
- two buttons: CV roasting&mentoring (is stub now)
- navigation up&down
- pdf upload and telegram nick input form
- transfer pdf via blob, increased blob size up to 10MB, saving in DB

2024-04-14 12:12 UTC, nekromant322 requested changes
бегло посмотрел с телефона, убрать косяки с чейджами для локального тестирования

2024-04-14 12:12 UTC, nekromant322 commented on docker-compose.yml
> +      POSTGRES_USER: root
А может не надо? Оно так сломается вообще-то в проде :)

2024-04-14 12:12 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/controller/SubmissionRestController.java
> +//    @PostMapping("/submit_name")
Убрать грязь

2024-04-14 12:12 UTC, nekromant322 commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${TELEGRAM_BOT_DB_PORT:5436}/review_bot
-//-

2024-04-14 12:40 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/controller/SubmissionRestController.java
> +    NewClientService newClientService;
Можификаторы для слабаков

2024-04-14 12:43 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +    private String tg_name;
Лучше назвать все-таки поле по-джавовски `tgName`, а в самой анноташке `@Column` присваивать значение из бд

2024-04-14 12:44 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +public class NewClient {
А новый клиент чего? (Это не придирка, мне просто непонятно в чем замес)

2024-04-14 12:45 UTC, etozhealexis commented on src/main/resources/static/submission/assets/cssandjs/submisson.js
> +    let tg_nick = document.getElementById("tg_name_input_form").value;
Тут тоже лучше сделать по-джавовски (уж джса вроде такой же должен быть кодстайл по названию переменных)

2024-04-14 12:46 UTC, etozhealexis commented on src/main/resources/static/submission/assets/cssandjs/submisson.js
> +    let tg_nick = document.getElementById("tg_name_input_form").value;
И методов!

2024-04-14 12:47 UTC, etozhealexis requested changes
Поправить замечания

2024-04-14 12:54 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +@Data
Не используй эту аннотацию для `@Entity`-классов, она сломана для них

2024-04-14 13:04 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/controller/SubmissionRestController.java
> +//        System.out.println("*************************");
и тут грязь

2024-04-14 13:04 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/controller/SubmissionRestController.java
> +        Blob blob = new javax.sql.rowset.serial.SerialBlob(pdfBlob.getBytes());
тут можно импорт заиспользовать

2024-04-14 13:05 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +    private Blob CVPdf;
Этот блоб кажется вполне может быть byte[]   
https://gist.github.com/vegaasen/7ffb86fe380f33655ba3c59fc28459e5

2024-04-14 13:08 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +public class NewClient {
Лучше будет ResumeAnalysisRequest

2024-04-15 06:07 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/NewClient.java
> +public class NewClient {
задание было создать формочку с двумя кнопками - резюме на прожарку и подписка на менторинг. и соответствующая логика. предположил, что этим будут пользоваться потенциально новые клиенты.

2024-04-15 15:44 UTC, closed without merging