new service & front redesign
nekromant322/review-report-bot pull request #41
Opened 2024-05-06 18:51 UTC by Vladislav812

- добавлен второй сервис - подписка на менторинг
- инпуты на лендинге аккуратно сложены один под другой
- соответственно, добавлена секция для второго сервиса
- добавлена подгрузка цены из свойств application
- все переведено на русский

2024-05-06 18:55 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/controller/ResumeAnalysisRequestRestController.java
> +    PriceProperties priceProperties;
private

2024-05-06 18:55 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +    private String lifePayNumber;
это номер телефона или номер транзакции? опять блин не понятно)

2024-05-06 18:55 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    MentoringSubscriptionRequestRepository mentoringSubscriptionRequestRepository;
private

2024-05-06 18:56 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    }
метод огромный получился  
го часть логики по мапингу вынесем в отдельный маппер, ну или хотя бы в метод

2024-05-06 18:57 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +        final String RESPONSE_FOR_MENTORING_SUBSCRIPTION = "Зарегистрирован и оплачен заказ %s на подписку на менторинг: \nтелефон: %s \nTelegram nickname: @%s";
у меня там есть целый класс с константами текстовыми, чтобы долго по коду не искать, когда надо поправить текстовки

2024-05-06 18:57 UTC, nekromant322 requested changes
поправить по замечаниям

2024-05-06 19:25 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    }
подскажи плз, что именно вынести

2024-05-06 19:30 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    }
` PaymentDetails paymentDetails = new PaymentDetails();
            paymentDetails.setNumber(lifePayResponse.getData().getNumber());
            paymentDetails.setStatus(PayStatus.UNREDEEMED.get());
            paymentDetails.setServiceType(ServiceType.MENTORING.get());
            paymentDetailsRepository.save(paymentDetails);`

2024-05-06 19:31 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    }
Можно еще воспользоваться @Builder для моделек, тогда будем не так монструозно выглядеть

2024-05-06 19:42 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +    private String alias;
final?

2024-05-06 19:43 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +    ServiceType(String alias) {
Можно заменить аннотациями ломбока

2024-05-06 19:43 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +    ServiceType(String alias) {
`get()` тоже

2024-05-06 19:44 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/controller/PaymentDetailsRestController.java
> +//        sendMessage(paymentDetails);
?? (Сори, смотрю с телефона, не могу нормально вчитаться)

2024-05-06 19:47 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +    @Override
Посмотри генерацию `@ToString`, там вполне можно прописывать те поля, которые нужны

2024-05-06 19:50 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +public enum ServiceType {
В целом не виду смысла в том, чтобы в енаме была строка, в которой содержится название. Насколько понял, это нужно для соответствия с бд, но как будто бы вполне можно для такой цели использовать вариацию без алиаса

2024-05-06 19:51 UTC, etozhealexis commented on src/main/java/com/nekromant/telegram/model/PaymentDetails.java
> +    private String serviceType;
Вот этого прикола не понял (зачем тогда енам нужен, если все равно в стринги все переводишь)

2024-05-06 19:53 UTC, etozhealexis requested changes
Ответить на комменты, посмотреть предложения

2024-05-06 19:55 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +public enum ServiceType {
Согласен
см `@Enumerated(EnumType.STRING)`

2024-05-06 20:05 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/controller/PaymentDetailsRestController.java
> +//        sendMessage(paymentDetails);
не уследил, это для локального тестирования, чтобы лишнее не отправлялось

2024-05-07 14:12 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/controller/ResumeAnalysisRequestRestController.java
> +    PriceProperties priceProperties;
done

2024-05-07 14:13 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +    private String lifePayNumber;
заменил везде на customerPhone и lifePayTransactionNumber;

2024-05-07 14:14 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    MentoringSubscriptionRequestRepository mentoringSubscriptionRequestRepository;
done

2024-05-07 14:18 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +    }
вынес в builder PaymentDetails, MentoringSubscriptionRequest и ResumeAnalysisRequest

2024-05-07 14:19 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/MentoringSubscriptionRequestService.java
> +        final String RESPONSE_FOR_MENTORING_SUBSCRIPTION = "Зарегистрирован и оплачен заказ %s на подписку на менторинг: \nтелефон: %s \nTelegram nickname: @%s";
добавил 4 константы

2024-05-07 14:19 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
> +        final String RESPONSE_FOR_RESUME_PROJARKA = "Зарегистрирован и оплачен заказ %s на разбор резюме: \nтелефон: %s \nTelegram nickname: @%s";
done

2024-05-07 14:22 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +    @Column(name = "tg_name")
такое же; убрал лишнее

2024-05-07 18:09 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +    @Override
done

2024-05-07 18:14 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/PaymentDetails.java
> +    private String serviceType;
в PaymentDetailsDTO статус уже стрингой определен. Опасался что-то в готовом ковырять.
в PaymentDetails положил полноценный enum, в modelMapper добавил конвертер String->enum

2024-05-07 18:17 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +public enum ServiceType {
@Enumerated(EnumType.STRING) не получится использовать, т.к в рабочую базу уже попало интовое поле.
Alias использовал для соответствия с PaymentDetailsDTO, там статус стрингой.
В enum оставил только значения, в modelMapper добавил конвертер String->enum

2024-05-07 18:18 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/contants/ServiceType.java
> +    ServiceType(String alias) {
уже неактуально, в enum остались только значения

2024-05-07 18:31 UTC, Vladislav812 reviewed
- внесены исправления по предыдущим замечениям
- исправлен нейминг главного контроллера (PricingController) и ендпойнты

2024-05-07 23:27 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/MentoringSubscriptionRequest.java
> +@Data
@Data в @Entity - не лучшая идея
лучше отдельно @Getter и @Setter

2024-05-07 23:27 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/PaymentDetails.java
>  @Data
тут я бы тоже убрал)

2024-05-07 23:27 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/ResumeAnalysisRequest.java
> +@Data
и туть

2024-05-09 15:06 UTC, nekromant322 approved these changes

2024-05-09 16:32 UTC, merged