Promocodes manipulation
nekromant322/review-report-bot pull request #48
Opened 2024-05-27 14:25 UTC by Vladislav812

- сделана админская панель для создания/удаления/вкл-выкл промокодов
- скидка задается в процентах от базовой стоимости
- счетчик использований
- на странице оплаты для клиента реализована пока только оплата по промокоду и только для прожарки резюме
- если промокод выключен или число использований исчерпано, выводится соответсвующее сообщение
- блок с вводом данных скрыт до ввода промокода и расчета скидки
- после успешного ввода имеющегося промокода отображается блок с вводом пользовательских данных, а блок с промокодом скрывается
- отображается цена с учетом скидки по промокоду
- в админской панели можно посмотреть все транзакции по данному коду (с любым статусом)

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/controller/PromocodeRestController.java
> +    @PostMapping("/promocode/add")
Меня ща на работе дрючат за то, что иногда не соблюдаю rest api naming conventions
https://restfulapi.net/resource-naming/ - тут в целом норм описано, как мне кажется
пункт 2.4 , в целом применен для всех методов этого контроллера

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/controller/PromocodeRestController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
Можно еще ResponseEntity.ok().build(); По мне как читаемее

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/model/Promocode.java
> +    private Set<PaymentDetails> paymentDetailsSet;
почему не просто paymentDetails?

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/controller/PromocodeRestController.java
> +    public ResponseEntity updateIsActive(@RequestBody Map isActiveMap) {
Можно сделать PromocodeUpdateDTO, если передаешь JSON сюда, и там уже вписать нужные тебе поля, используемые при обновлении

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/repository/PromocodeRepository.java
> +    Promocode findByPromocodeText(String promocodeText);
Текст промокода всегда будет уникальным? Не будет ситуаций, когда по тексту можешь найтись 2+ промокода, а мы ожидаем 1, судя по запросу?

2024-05-27 15:21 UTC, NikitosikQQ commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
>      public void sendCVToMentorForAnalysis(PaymentDetails paymentDetails) {
Думаю тут можно и @Transactional навесить

2024-05-27 15:59 UTC, NikitosikQQ commented on src/main/resources/static/js/promocode_panel.js
> +            alert("Текст промокода должен быть уникальным!");
Как будто лучше эту проверку делать на бэке..? @nekromant322 как считаешь?
А уже при обработке ошибки сохранения(в случае неуникальности) делать этот алерт

2024-05-28 15:54 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/repository/PromocodeRepository.java
> +    Promocode findByPromocodeText(String promocodeText);
думаю, да, иначе теряется вся логика использования промокода пользователем. он должен ввести промокод и получить однозначный ответ

2024-05-28 17:07 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/controller/PromocodeRestController.java
> +    @PostMapping("/promocode/add")
done

2024-05-28 17:07 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/model/Promocode.java
> +    private Set<PaymentDetails> paymentDetailsSet;
так paymentDetails - это сущность, а paymentDetailsSet - набор сущностей..

2024-05-28 17:09 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/controller/PromocodeRestController.java
> +    public ResponseEntity updateIsActive(@RequestBody Map isActiveMap) {
уже не используется, убрал

2024-05-28 17:10 UTC, Vladislav812 commented on src/main/resources/static/js/promocode_panel.js
> +            alert("Текст промокода должен быть уникальным!");
ждем авторитетного решения

2024-05-28 23:29 UTC, Vladislav812 commented on src/main/resources/static/js/promocode_panel.js
> +            alert("Текст промокода должен быть уникальным!");
done

2024-06-01 11:56 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/Promocode.java
> +    private Set<PaymentDetails> paymentDetailsSet;
> так paymentDetails - это сущность, а paymentDetailsSet - набор сущностей..

да, это указано в типе  к счастью
из-за такого нейминга там дальше сбивает с толку абсолютно findByPaymentDetailsSetNumber  , я голову ломал че это за фигня, по хешу сета чтоли ищешь,а разгадка тут была

2024-06-01 11:56 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/PromocodeService.java
> +    PromocodeRepository promocodeRepository;
private

2024-06-01 11:58 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
>      public void sendCVToMentorForAnalysis(PaymentDetails paymentDetails) {
не хватает транзакции в этом методе, согласен, а еще его нейминг сбивает с толку жестко  
sendCVToMentorForAnalysis на самом деле инкрементит использования промокодов и обновляет информацию по платежке!

2024-06-01 11:59 UTC, nekromant322 requested changes
надо прикрыть ендпоинт с админ панелью от чужих ручонок обязательно

2024-06-04 10:39 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/config/PrepopulateSecurityAccount.java
> +
тут че-т не видать проверки никакой, постоянно сейвы в базу  
пароль сомнительный  
мб просто добавить енв, а я в сикретики запихну  
вообще кажется из базы брать - лишнее, можно же просто inmemory заюзать в секурити конфигурации

2024-06-04 10:41 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
> +        super.smth("Payment failed: " + paymentDetails);
че за smth?

2024-06-04 10:41 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
> +//        ResumeAnalysisRequestService.log.info("Payment failed: " + paymentDetails);
а почему закоменчено?

2024-06-04 10:41 UTC, nekromant322 requested changes
допилить авторизацию, думаю можно обойтись единственной учеткой без связи с базой вовсе

2024-06-04 14:20 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
> +        super.smth("Payment failed: " + paymentDetails);
эт я проверял, как логирование подкласса из родительского класса будет работать

2024-06-04 14:20 UTC, Vladislav812 commented on src/main/java/com/nekromant/telegram/service/ResumeAnalysisRequestService.java
> +//        ResumeAnalysisRequestService.log.info("Payment failed: " + paymentDetails);
тож самое, что выше. вначале попросил не смотреть пока

2024-06-04 16:25 UTC, nekromant322 commented on src/main/java/com/nekromant/telegram/model/UserInfo.java
> +    @Transient
я бы отпилил и это, можно внутренний класс внутри секурити конфига создать :)

2024-06-05 01:53 UTC, nekromant322 commented on src/main/resources/application.yml
> +  password: ${OWNER_PASSWORD}
надо прокинуть в докер композ, чтоб из кредов на гитхабе сюда попало

2024-06-05 01:53 UTC, nekromant322 requested changes
прокинуть енвы и погнали

2024-06-05 13:31 UTC, nekromant322 approved these changes

2024-06-05 13:36 UTC, merged